### PR TITLE
Bugfix/ls24002872/ds double definition

### PR DESCRIPTION
**Pull request by dom-apuliasoft**
## Description

In some cases (such as adding additional fields to DS based on EXTNAME) some fields were declared twice. This PR fixes this behaviour.

Related to:
- LS24002872

Might be also related to #531 

## Checklist:
- [x] There are tests regarding this feature
- [x] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [x] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

### CODE REVIEW

**Review by lanarimarco — COMMENTED** [review]
You could try integrating only your tests into the current develop branch. 
Let me know.

**Comment by dom-apuliasoft** [comment]
@lanarimarco the issues appears to be effectively fixed by the merging of #531. This PR can safely be closed or merged in order to improve test coverage (I reverted the significant changes and only left the new test case).

**Comment by lanarimarco** [comment]
> @lanarimarco the issues appears to be effectively fixed by the merging of #531. This PR can safely be closed or merged in order to improve test coverage (I reverted the significant changes and only left the new test case).

I will merge it, thanks

**Review by lanarimarco — APPROVED** [review]
Ok

**Pull request merged**
