### PR TITLE
Bugfix/nw23001440/code in mock

### PR DESCRIPTION
**Pull request by davidepalladino-apuliasoft**
## Description
For this task, I created the `ExfmtStmt`, `ReadcStmt` and `UnlockStmt` so that Jariko no longer crashes when there are `EXMT`, `READC` and `UNLOCK` operators. There are three respective `.rpgle` files with those operators.

## Checklist:
- [x] There are tests regarding this feature
- [x] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [X] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

### CODE REVIEW

**Review by lanarimarco — COMMENTED** [review]
Good job, but I am not sure if is right that the mock-implementation does not have to throw any error at runtime.
As far as regard the tests it seems to me that are missing the Sxx_Tyy_Pzz test cases.
However, for both questions ask Maria Paola.

**Comment by lanarimarco** [comment]
Do we know how to move on?

**Comment by davidepalladino-apuliasoft** [comment]
> Do we know how to move on?

I'm waiting a feedback from Mariapaola about the tests with those operators.

**Comment by davidepalladino-apuliasoft** [comment]
> > > Do we know how to move on?
> > 
> > 
> > I'm waiting a feedback from Mariapaola about the tests with those operators.
> 
> If you agree I would merge

Yes, I agree.

**Review by lanarimarco — APPROVED** [review]
Ok

**Comment by davidepalladino-apuliasoft** [comment]
> Resolve conficts

Done

**Review by lanarimarco — APPROVED** [review]
Ok

**Pull request merged**
