### PR TITLE
Bugfix/nw23001440/like with static

### PR DESCRIPTION
**Pull request by lanarimarco**
## Description

- Fix subrocedure `D LIKE`: D spec defined like a variable outside the subprocedure was not resolved properly
- Fix `RETURN`: Program did not return properly if `RETURN` was inside a block of composite statement (for exemple `IF` `ENDIF)`
- Feat add `STATIC` keyword support

Related to T02_A70_P01

## Checklist:
- [x] There are tests regarding this feature
- [x] The code follows the Kotlin conventions (run `./gradlew ktlintCheck`)
- [x] The code passes all tests (run `./gradlew check`)
- [ ] There is a specific documentation in the `docs` directory

### CODE REVIEW

**Comment by lanarimarco** [comment]
@cosentino-smeup Your review might be helpful because this branch was yours

**Comment by cosentino-smeup** [comment]
You must resolve the conflicts

**Comment by lanarimarco** [comment]
> You must resolve the conflicts

Done

**Comment by cosentino-smeup** [comment]
If I got it right, the LIKE inside the procedure is basically the same implementation I have done initially with the use of the parentDataDefinitions variable (where you added a default).

The STATIC keyword management instead is complete new. The static "Scope" Enum became a class so you can create as many instances as the procedures which are named after the procedure name. You implemented the beforeInitialization and afterInitialization in the FunctionInterpreter (the subprocedure) to initialize the StaticSymbolTable. Inside the StaticSymbolTable there is a memorySliceMgr that is used to restore the status of the SymbleTable across the processes.

**Comment by lanarimarco** [comment]
> The STATIC keyword management instead is completely new. The "Scope" Enum became a class so you can create as many instances as the procedures which are named after the procedure name. You implemented the beforeInitialization and afterInitialization in the FunctionInterpreter (the subprocedure) to initialize the StaticSymbolTable. Inside the StaticSymbolTable there is a memorySliceMgr that is used to restore the status of the SymbleTable across the processes and it maintains the variables value for the specific procedure

Perfect!!!

**Comment by cosentino-smeup** [comment]
> > The STATIC keyword management instead is completely new. The "Scope" Enum became a class so you can create as many instances as the procedures which are named after the procedure name. You implemented the beforeInitialization and afterInitialization in the FunctionInterpreter (the subprocedure) to initialize the StaticSymbolTable. Inside the StaticSymbolTable there is a memorySliceMgr that is used to restore the status of the SymbleTable across the processes and it maintains the variables value for the specific procedure
> 
> Perfect!!!

I don't understand how static variables get destroyed when the caller program complete the execution.

**Comment by lanarimarco** [comment]
Indeed It does not get destroyed because static variables scope is for
procedure and job id.





[image: smeup] <https://www.smeup.com>
Marco Lanari
R&D Department - Developer

Office: 0521940611 <00390521940611>
www.smeup.com

*SMEUP LAB SRL*
Via Carra, 8 - 43122 Parma (PR)



Il giorno mer 28 feb 2024 alle 07:34 cosentino-smeup <
***@***.***> ha scritto:

**Review by cosentino-smeup — APPROVED** [review]
Ok

**Pull request merged**
