### PR TITLE
Bugfix/LS24004081/Z-ADD with Scalar to Array

### PR DESCRIPTION
**Pull request by davidepalladino-apuliasoft**
## Description
This work resolves an assignment of a **scalar value** to an **array** defined as Data Struct's field. For example:
```
     D D5COSO        E DS                  EXTNAME(D5COSO0F)
     D  D50                                DIM(99) LIKE(D$C001) INZ
     D                                             OVERLAY(D5COSO:88)

     C                   Z-ADD     1             D50
```

In addition, was analyzed and fixed an assignment of a **scalar value** to an **array** defined as Standalone. For example:
```
     D  D50            S              5  0 DIM(99) INZ

     C                   Z-ADD     1             D50
```

### Technical notes
To achieve the goal, I improved `InternalInterpreter.set` when `value` (which the source) is a scalar instead an array, under `FieldDefinition`'s branch. 

Related to #LS24004081

## Checklist:
- [x] If this feature involves RPGLE fixes or improvements, they are well-described in the summary.
- [x] There are tests for this feature.
- [x] RPGLE code used for tests is easily understandable and includes comments that clarify the purpose of this feature.
- [x] The code follows Kotlin conventions (run `./gradlew ktlintCheck`).
- [x] The code passes all tests (run `./gradlew check`).
- [ ] Relevant documentation is included in the `docs` directory.

### CODE REVIEW

**Comment by davidepalladino-apuliasoft** [comment]
> Was the issue related only to when an array is defined in a data structure field, or was the issue more general? I’m not sure, maybe it's a silly question, but let me know.

The issue was related only for this case. If you want, I can check the existence on Jariko where the array is a  Standalone field. In case it miss, I can create a test from AS400 and run it on Jariko. What do you think?

**Comment by lanarimarco** [comment]
> > Was the issue related only to when an array is defined in a data structure field, or was the issue more general? I’m not sure, maybe it's a silly question, but let me know.
> 
> The issue was related only for this case. If you want, I can check the existence on Jariko where the array is a Standalone field. In case it miss, I can create a test from AS400 and run it on Jariko. What do you think?

I would try, thank you.

**Comment by davidepalladino-apuliasoft** [comment]
> > > Was the issue related only to when an array is defined in a data structure field, or was the issue more general? I’m not sure, maybe it's a silly question, but let me know.
> > 
> > 
> > The issue was related only for this case. If you want, I can check the existence on Jariko where the array is a Standalone field. In case it miss, I can create a test from AS400 and run it on Jariko. What do you think?
> 
> I would try, thank you.

You're welcome! I'm going to try after a little analysis of another task.

**Comment by davidepalladino-apuliasoft** [comment]
Made draft for a new error after test case where the array is a Standalone field.

**Review by lanarimarco — APPROVED** [review]

**Pull request merged**
