### PR TITLE
chore: update dependabot.yml to include gradle dependencies updates

### PR DESCRIPTION
**Pull request by paolofacchinetti**
## Description

Add a dependabot configuration to do dependency updates for the `gradle` ecosystem

## Checklist:
- [ ] If this feature involves RPGLE fixes or improvements, they are well-described in the summary.
- [ ] There are tests for this feature.
- [ ] RPGLE code used for tests is easily understandable and includes comments that clarify the purpose of this feature.
- [ ] The code follows Kotlin conventions (run `./gradlew ktlintCheck`).
- [ ] The code passes all tests (run `./gradlew check`).
- [ ] Relevant documentation is included in the `docs` directory.

### CODE REVIEW

**Comment by paolofacchinetti** [comment]
I have tested the setup locally using [dependabot/cli](https://github.com/dependabot/cli), here is part of the output which proves that dependabot works properly and also checks for dependencies of the gradle submodules in this repo

```
updater | +-------------------------------------------------------------------------+
updater | |                   Changes to Dependabot Pull Requests                   |
updater | +---------+---------------------------------------------------------------+
updater | | created | org.jlleitschuh.gradle:ktlint-gradle ( from 8.2.0 to 12.1.1 ) |
updater | | created | io.github.gradle-nexus.publish-plugin ( from 1.1.0 to 2.0.0 ) |
updater | | created | org.ajoberstar.grgit ( from 5.0.0-rc.3 to 5.3.0 )             |
updater | | created | com.github.ajalt:clikt ( from 2.1.0 to 3.5.2 )                |
updater | | created | com.github.ziggy42:kolor ( from 0.0.2 to 1.0.0 )              |
updater | +---------+---------------------------------------------------------------+
```

**Comment by lanarimarco** [comment]
> I have tested the setup locally using [dependabot/cli](https://github.com/dependabot/cli), here is part of the output which proves that dependabot works properly and also checks for dependencies of the gradle submodules in this repo
> 
> ```
> updater | +-------------------------------------------------------------------------+
> updater | |                   Changes to Dependabot Pull Requests                   |
> updater | +---------+---------------------------------------------------------------+
> updater | | created | org.jlleitschuh.gradle:ktlint-gradle ( from 8.2.0 to 12.1.1 ) |
> updater | | created | io.github.gradle-nexus.publish-plugin ( from 1.1.0 to 2.0.0 ) |
> updater | | created | org.ajoberstar.grgit ( from 5.0.0-rc.3 to 5.3.0 )             |
> updater | | created | com.github.ajalt:clikt ( from 2.1.0 to 3.5.2 )                |
> updater | | created | com.github.ziggy42:kolor ( from 0.0.2 to 1.0.0 )              |
> updater | +---------+---------------------------------------------------------------+
> ```

Ok

**Review by lanarimarco — APPROVED** [review]
I am really scared about this:
`org.jlleitschuh.gradle:ktlint-gradle ( from 8.2.0 to 12.1.1 )`

# The ktlint-gradle odissey
- At this point, the check on the entire project failed because Gradle indicated a declaration error in the Gradle script of `ktlintMainSrcCheck`, which is related to the `ktlint-gradle` plugin used for formatting checks.
- Since the version was very old (8.2.0), I updated it to the latest version, 11.3.2.
- The plugin became monstrously stricter, detecting thousands of formatting errors. Among other things, it also didn't like the `mypackage.*` imports.
- I tried to fix it, but when I ran the check again, those errors didn't go away.
- I found out that IntelliJ, by default, automatically replaces imports with `miopackage.*` if there are more than three classes imported from the same package. I then realized that this behavior can be disabled.
- The fixes for `mypackage.*` were getting more and more complicated, especially with the classes automatically generated by the parser. Since the classes are generated after the check that failed, it was hard to understand whether imports were missing because I had forgotten to add them or because the imports couldn't be made since the class hadn't been generated by the parser yet. After hours of trying to fix it, I gave up and reverted the `ktlint-gradle` version to 8.2.0.

When I speak about the context I mean just these stuff

**Comment by paolofacchinetti** [comment]
> I am really scared about this: `org.jlleitschuh.gradle:ktlint-gradle ( from 8.2.0 to 12.1.1 )`
> 
> # The ktlint-gradle odissey
> * At this point, the check on the entire project failed because Gradle indicated a declaration error in the Gradle script of `ktlintMainSrcCheck`, which is related to the `ktlint-gradle` plugin used for formatting checks.
> * Since the version was very old (8.2.0), I updated it to the latest version, 11.3.2.
> * The plugin became monstrously stricter, detecting thousands of formatting errors. Among other things, it also didn't like the `mypackage.*` imports.
> * I tried to fix it, but when I ran the check again, those errors didn't go away.
> * I found out that IntelliJ, by default, automatically replaces imports with `miopackage.*` if there are more than three classes imported from the same package. I then realized that this behavior can be disabled.
> * The fixes for `mypackage.*` were getting more and more complicated, especially with the classes automatically generated by the parser. Since the classes are generated after the check that failed, it was hard to understand whether imports were missing because I had forgotten to add them or because the imports couldn't be made since the class hadn't been generated by the parser yet. After hours of trying to fix it, I gave up and reverted the `ktlint-gradle` version to 8.2.0.
> 
> When I speak about the context I mean just these stuff

I think this topic should be moved to a new Issue since it's big enough to be worthy of discussion and is unrelated to dependabot. I'll open it myself

**Comment by lanarimarco** [comment]
> > I am really scared about this: `org.jlleitschuh.gradle:ktlint-gradle ( from 8.2.0 to 12.1.1 )`
> > # The ktlint-gradle odissey
> > 
> > * At this point, the check on the entire project failed because Gradle indicated a declaration error in the Gradle script of `ktlintMainSrcCheck`, which is related to the `ktlint-gradle` plugin used for formatting checks.
> > * Since the version was very old (8.2.0), I updated it to the latest version, 11.3.2.
> > * The plugin became monstrously stricter, detecting thousands of formatting errors. Among other things, it also didn't like the `mypackage.*` imports.
> > * I tried to fix it, but when I ran the check again, those errors didn't go away.
> > * I found out that IntelliJ, by default, automatically replaces imports with `miopackage.*` if there are more than three classes imported from the same package. I then realized that this behavior can be disabled.
> > * The fixes for `mypackage.*` were getting more and more complicated, especially with the classes automatically generated by the parser. Since the classes are generated after the check that failed, it was hard to understand whether imports were missing because I had forgotten to add them or because the imports couldn't be made since the class hadn't been generated by the parser yet. After hours of trying to fix it, I gave up and reverted the `ktlint-gradle` version to 8.2.0.
> > 
> > When I speak about the context I mean just these stuff
> 
> I think this topic should be moved to a new Issue since it's big enough to be worthy of discussion and is unrelated to dependabot. I'll open it myself

I agree

**Pull request merged**
